const FORM_TYPE = ['BROADCAST','GROUP', 'INDIVIDUAL']
const FORM_STATUS = ['DRAFT', 'PUBLISHED', 'COMPLETED']
const USER_STATUS = ['ACTIVE', 'INACTIVE']
const ACTIVITY_TYPE = [
    'LOGIN',
    'LOGOUT',
    'SIGNUP',
    'CREATE_FORM',
    'UPDATE_FORM',
    'DELETE_FORM',
    'PUBLISH_FORM',
    'CREATE_QUESTION',
    'UPDATE_QUESTION',
    'DELETE_QUESTION',
    'CREATE_OPTION',
    'UPDATE_OPTION',
    'DELETE_OPTION',
    'FORM_SUBMIT',
    'FORM_VIEWED',
]

export { FORM_TYPE, FORM_STATUS, USER_STATUS, ACTIVITY_TYPE }